-- 2 / SQL LDD

-- 2
ALTER TABLE Match
ADD (
-- 2.1 
CONSTRAINT FK_MatchJoueur FOREIGN KEY (NJ) REFERENCES Joueur(NJ),

--2.2
CONSTRAINT FK_MatchEquipe1 FOREIGN KEY (NE1) REFERENCES Equipe(NE),
CONSTRAINT FK_MatchEquipe2 FOREIGN KEY (NE2) REFERENCES Equipe(NE),

--2.3   
CONSTRAINT FK_MatchArbitre FOREIGN KEY (PREA,NOMA) REFERENCES Arbitre(PREA,NOMA),

--2.4
CONSTRAINT CHK_MatchScore CHECK (SCR1>=0),
CONSTRAINT CHK_MatchScore2 CHECK (SCR2>=0),

--2.5
CONSTRAINT CHK_MatchDuree CHECK (JRN BETWEEN 1 AND 5),

--2.6
CONSTRAINT CHK_MatchAdversaire CHECK (NE2 <> NE2),

--2.7
CONSTRAINT UC_MatchAdversaire UNIQUE (NE1,NE2)
);

--3
SELECT OBJECT_NAME, CREATED
FROM USER_OBJECTS;

-- 3 / SQL LMD
